devices:
- hostname: R1
  ip_address: 192.168.233.130
  password: env:R1_PASS
  type: mikrotik
  username: admin
- hostname: R2
  ip_address: 192.168.233.131
  password: env:R2_PASS
  type: mikrotik
  username: admin
- hostname: R3
  ip_address: 192.168.233.132
  password: env:R3_PASS
  type: mikrotik
  username: admin
- hostname: R4
  ip_address: 192.168.233.133
  password: env:R4_PASS
  type: mikrotik
  username: admin
